### ISSUE TITLE
Bad HTML file generated

### ISSUE THREAD

**Issue by ChrisWakefield** [MD-Anderson-Bioinformatics/NGCHM-R#30]
We received an email:

I have recently discovered ng-chm and I  am really impressed by the performance and features of the package.
 
I have built the last release of ngchmr  (0.13.0) from github with the dependencies. Using the TCGA sample, the generation of  the html seems OK, however there is an error in the generated html ("" literal not terminated before end of script, line 20:59712 in the firefox console, I have the same error with chrome or by editing the source in visual studio code).
 
I have built the package on windows (R 3.6) and linux (R 4.1.3) giving the same error.
 
You can download the generated html (I have limited the matrix to a 2x2 size) following this link ([https://filesender.renater.fr/?s=download&token=05eaf4a5-5300-47c7-b057-3dc034e39bf7](https://urldefense.com/v3/__https:/filesender.renater.fr/?s=download&token=05eaf4a5-5300-47c7-b057-3dc034e39bf7__;!!PfbeBCCAmug!nLBQlwn7TINuwEYfXPMKujuVxrXqGqTIKLgFa4mnBBTDJz8VwlR1b3uUwiHaomZcJ_WUOkogu4vOj1jSHATVrNY9VZ975n4lbDLO$)).
 
Note that generating pdf or ngchm files are OK.
 
Thanks for your advice.
Best regards,
Jean-Philippe

**Comment by ChrisWakefield** [comment]
Confirmed as consistently repeatable.
This looks to be a bug [somewhere] in the NGCHM_Widgetizer portion of [NG-CHM](https://github.com/MD-Anderson-Bioinformatics/NG-CHM) introduced in the latest 2.22.x releases.
@jmelott

**Comment by jmelott** [comment]
File with error (In case link in above message disappears)
[tcga-brca (1).zip](https://github.com/MD-Anderson-Bioinformatics/NGCHM-R/files/8893397/tcga-brca.1.zip)

**Comment by jmelott** [comment]
I verified that the code worked to create a valid HTML and ngchm file following the instructions on https://md-anderson-bioinformatics.github.io/NGCHM-R/articles/create-a-ng-chm.html in the 2.22.2 release.

**Comment by ChrisWakefield** [comment]
Thanks James!  Closing as fixed.
