### ISSUE TITLE
Is this still an active site? I have question about the command "chmViewer()"

### ISSUE THREAD

**Issue by aliciachen06** [MD-Anderson-Bioinformatics/NGCHM-R#32]
Is the command still working for "chmViewer()"?
It would work when I use the browser through local host 8787. However, it is not working in our Rstudio server. 
Could I get help?
Thank you,

**Comment by ChrisWakefield** [comment]
@aliciachen06 
Absolutely.  Thanks for contacting us.

Try the function plot() instead, or chmBrowse().  See https://md-anderson-bioinformatics.github.io/NGCHM-R/reference/plot.ngchmVersion2.html .

I don't find "chmViewer" in the current code.  The video and corresponding docker containers that have chmViewer is based on NGCHM-R version 0.12.6, while the current code is 0.12.11.

If plot() doesn't solve it, then are you using the Docker container, or have you installed the NGCHM-R package on your own RStudio server?

Regards!
Chris

**Comment by ChrisWakefield** [comment]
@aliciachen06 
An update:
chmViewer is a function added in building the docker image:

`chmViewer <- function() { rstudioapi::viewer(file.path(tempdir(), "ngChmApp.html")); }
`
and the code above is written into the /usr/local/lib/R/etc/Rprofile.site file.  If your RStudio server has a different RProfile.site, it won't be available (from us).  You can define the function yourself using the one line above.

**Comment by aliciachen06** [comment]
Hi,Thank you. Dr. Broom is replying to me too. He is taking care of the issue now for me.
Alicia
    On Wednesday, October 5, 2022 at 02:16:32 PM PDT, Chris Wakefield ***@***.***> wrote:  
 
 


@aliciachen06
An update:
chmViewer is a function added in building the docker image:

chmViewer <- function() { rstudioapi::viewer(file.path(tempdir(), "ngChmApp.html")); } 
and the code above is written into the /usr/local/lib/R/etc/Rprofile.site file. If your RStudio server has a different RProfile.site, it won't be available (from us). You can define the function yourself using the one line above.

**Comment by marohrdanz** [comment]
Closed after discussion.
